"""
Deterministic Mission Orchestrator
===================================
Replaces the random simulator with a real task lifecycle engine.

Design is inspired by the sequential-steps pattern in:
  mission_control/core/orchestrator.py

Each tick executes six explicit, ordered steps — no randomness.

Public API (unchanged so main.py needs no edits):
    start()  → launches background thread
    stop()   → signals thread to stop and joins it

Tick interval: TICK_INTERVAL seconds (default 2s).

Task lifecycle:
    queued ──► running ──► completed
                  │
                  └──► (agent gains capacity back after completion)

Mission lifecycle:
    planning/active ──► completed ──► (restart after RESTART_DELAY)
"""

import json
import os
import threading
import time
import uuid
from datetime import datetime, timezone

from .database import SessionLocal
from .models import AgentModel, MissionModel, TaskModel, ActivityEventModel
from . import scribe

# ─── Configuration ────────────────────────────────────────────────────────────

TICK_INTERVAL = 2.0       # seconds between orchestrator ticks
RESTART_DELAY = 45.0      # seconds a completed mission stays done before recycling

# Set AUTO_RECYCLE_MISSIONS=false (or 0 / no) in the environment to keep
# completed missions permanently completed.  Defaults to true so the demo
# keeps cycling without manual intervention.
AUTO_RECYCLE_MISSIONS: bool = os.getenv(
    "AUTO_RECYCLE_MISSIONS", "true"
).strip().lower() in ("1", "true", "yes")

# How much progress (%) a task gains per tick, by priority.
# At TICK_INTERVAL=2s: critical completes in ~34 ticks (~68s from 0%).
# Seeded tasks start at 30–68% so they complete much sooner.
PROGRESS_RATE: dict[str, float] = {
    "critical": 3.0,
    "high":     2.0,
    "medium":   1.5,
    "low":      1.0,
}

# Maximum number of concurrently running tasks per agent role.
AGENT_CAPACITY: dict[str, int] = {
    "agent-orchestrator": 5,
    "agent-researcher":   2,
    "agent-coder":        2,
    "agent-writer":       1,
    "agent-analyst":      2,
    "agent-reviewer":     1,
    "agent-planner":      1,
    "agent-executor":     3,
}

# Priority order for starting queued tasks (highest first).
PRIORITY_ORDER = ["critical", "high", "medium", "low"]

# ─── Thread state ─────────────────────────────────────────────────────────────

_thread: threading.Thread | None = None
_stop_event = threading.Event()

# In-memory record of when each mission completed (mission_id → wall-clock time).
# Used to decide when to recycle a completed mission.
_mission_completed_at: dict[str, float] = {}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _emit(
    db,
    *,
    event_type: str,
    agent_id: str,
    agent_name: str,
    message: str,
    metadata: dict | None = None,
) -> None:
    """Write one ActivityEvent row, generated by a real state transition."""
    evt = ActivityEventModel(
        id=f"evt-{uuid.uuid4().hex[:16]}",
        type=event_type,
        agent_id=agent_id,
        agent_name=agent_name,
        message=message,
        timestamp=_now_iso(),
        event_metadata=json.dumps(metadata) if metadata else None,
    )
    db.add(evt)


# ─── Step 1 — Advance running tasks ──────────────────────────────────────────

def _step_advance_running(db) -> list[TaskModel]:
    """
    Add PROGRESS_RATE[priority] to every running task.
    Returns the list of tasks that just crossed 100% (ready to be completed).
    """
    running = db.query(TaskModel).filter(TaskModel.status == "running").all()
    finished: list[TaskModel] = []

    for task in running:
        rate = PROGRESS_RATE.get(task.priority, 1.5)
        task.progress = round(min(task.progress + rate, 100.0), 1)
        if task.progress >= 100.0:
            finished.append(task)

    return finished


# ─── Step 2 — Complete finished tasks ────────────────────────────────────────

def _step_complete_tasks(db, finished: list[TaskModel]) -> None:
    """
    Transition finished tasks to 'completed' and update their agents.
    Emits one task_completed event per task.
    """
    now = _now_iso()

    for task in finished:
        task.status = "completed"
        task.progress = 100.0
        task.completed_at = now

        # Scribe (agent-writer) generates a real text deliverable on completion.
        if task.assigned_agent_id == "agent-writer" and not task.output:
            task.output = scribe.generate_output(task.title, task.description)

        agent = db.query(AgentModel).filter(AgentModel.id == task.assigned_agent_id).first()
        if agent:
            agent.tasks_active = max(0, (agent.tasks_active or 0) - 1)
            agent.tasks_completed = (agent.tasks_completed or 0) + 1
            agent.last_seen = now

            # Build optional metadata: include output preview for Scribe tasks.
            meta: dict | None = None
            if task.output:
                preview = task.output[:150].replace("\n", " ").strip()
                meta = {"output_preview": preview, "task_id": task.id}

            _emit(
                db,
                event_type="task_completed",
                agent_id=agent.id,
                agent_name=agent.name,
                message=f"{agent.name} completed \"{task.title}\"",
                metadata=meta,
            )


# ─── Step 3 — Start queued tasks ─────────────────────────────────────────────

def _step_start_queued(db) -> None:
    """
    Promote queued tasks to running when their assigned agent has capacity.

    Tasks are considered in priority order (critical → high → medium → low).
    Within the same priority, earlier created_at tasks go first.
    Emits one task_started event per task that starts.
    """
    now = _now_iso()

    # Build a live map of currently running task counts per agent.
    running_counts: dict[str, int] = {}
    running_tasks = db.query(TaskModel).filter(TaskModel.status == "running").all()
    for t in running_tasks:
        running_counts[t.assigned_agent_id] = running_counts.get(t.assigned_agent_id, 0) + 1

    # Work through queued tasks by priority, then age.
    for priority in PRIORITY_ORDER:
        queued = (
            db.query(TaskModel)
            .filter(TaskModel.status == "queued", TaskModel.priority == priority)
            .order_by(TaskModel.created_at)
            .all()
        )

        for task in queued:
            agent_id = task.assigned_agent_id
            capacity = AGENT_CAPACITY.get(agent_id, 1)
            current_load = running_counts.get(agent_id, 0)

            if current_load >= capacity:
                continue  # agent is at capacity — skip for this tick

            # Start the task.
            task.status = "running"
            task.started_at = now
            running_counts[agent_id] = current_load + 1

            agent = db.query(AgentModel).filter(AgentModel.id == agent_id).first()
            if agent:
                agent.tasks_active = (agent.tasks_active or 0) + 1
                agent.status = "busy"
                agent.last_seen = now

                _emit(
                    db,
                    event_type="task_started",
                    agent_id=agent.id,
                    agent_name=agent.name,
                    message=f"{agent.name} started \"{task.title}\"",
                )


# ─── Step 4 — Update mission progress ────────────────────────────────────────

def _step_update_mission_progress(db) -> None:
    """
    Recompute each active/planning mission's progress as:
        (number of completed tasks / total tasks) × 100
    """
    active_missions = (
        db.query(MissionModel)
        .filter(MissionModel.status.in_(["active", "planning"]))
        .all()
    )

    for mission in active_missions:
        all_tasks = db.query(TaskModel).filter(TaskModel.mission_id == mission.id).all()
        if not all_tasks:
            continue
        n_completed = sum(1 for t in all_tasks if t.status == "completed")
        mission.progress = round((n_completed / len(all_tasks)) * 100.0, 1)


# ─── Step 5 — Close completed missions ───────────────────────────────────────

def _step_close_missions(db) -> None:
    """
    If every task in an active mission is completed, mark the mission as
    completed and emit a handoff event from the orchestrator.
    """
    now = _now_iso()
    active_missions = (
        db.query(MissionModel)
        .filter(MissionModel.status.in_(["active", "planning"]))
        .all()
    )

    for mission in active_missions:
        all_tasks = db.query(TaskModel).filter(TaskModel.mission_id == mission.id).all()
        if not all_tasks:
            continue
        if all(t.status == "completed" for t in all_tasks):
            mission.status = "completed"
            mission.progress = 100.0
            _mission_completed_at[mission.id] = time.time()

            _emit(
                db,
                event_type="handoff",
                agent_id="agent-orchestrator",
                agent_name="Pymmys Core",
                message=f"Mission \"{mission.name}\" completed — all {len(all_tasks)} tasks done",
            )


# ─── Step 6 — Sync agent statuses ────────────────────────────────────────────

def _step_sync_agent_statuses(db) -> None:
    """
    Set each agent's status from their live task_active count:
      tasks_active > 0  →  busy
      tasks_active == 0 →  online   (they were previously idle/busy)
    Does not touch agents that are already 'idle' with no tasks — that is a
    stable resting state and we leave it as-is.
    """
    agents = db.query(AgentModel).all()
    for agent in agents:
        active = agent.tasks_active or 0
        if active > 0:
            agent.status = "busy"
        elif agent.status == "busy":
            # Just finished all tasks — transition to online.
            agent.status = "online"


# ─── Step 7 — Recycle completed missions ─────────────────────────────────────

def _step_recycle_missions(db) -> None:
    """
    After RESTART_DELAY seconds, reset a completed mission and all its tasks
    back to their initial states so the orchestrator keeps running.

    Skipped entirely when AUTO_RECYCLE_MISSIONS is False — completed missions
    stay completed and outputs are preserved.

    Reset rules:
      - Mission  → status=active, progress=0
      - Tasks    → status=queued, progress=0, started_at=None, completed_at=None,
                   output=None  (so Scribe regenerates fresh output next cycle)
    """
    if not AUTO_RECYCLE_MISSIONS:
        return

    now_t = time.time()
    now_iso = _now_iso()

    completed_missions = (
        db.query(MissionModel)
        .filter(MissionModel.status == "completed")
        .all()
    )

    for mission in completed_missions:
        completed_at = _mission_completed_at.get(mission.id, 0.0)
        if now_t - completed_at < RESTART_DELAY:
            continue  # not ready yet

        # Reset the mission.
        mission.status = "active"
        mission.progress = 0.0
        _mission_completed_at.pop(mission.id, None)

        # Reset all tasks in this mission.
        tasks = db.query(TaskModel).filter(TaskModel.mission_id == mission.id).all()
        for task in tasks:
            task.status = "queued"
            task.progress = 0.0
            task.started_at = None
            task.completed_at = None
            task.output = None

        _emit(
            db,
            event_type="message_sent",
            agent_id="agent-orchestrator",
            agent_name="Pymmys Core",
            message=f"Mission \"{mission.name}\" restarted — new execution cycle beginning",
        )


# ─── Main orchestrator tick ───────────────────────────────────────────────────

def _tick(db) -> None:
    """
    One full orchestration cycle.  Mirrors the STEPS pattern from
    mission_control/core/orchestrator.py — each sub-function has a single,
    named responsibility and executes in a fixed order.

    Step 1  Advance   — add progress to every running task
    Step 2  Complete  — finalise tasks that hit 100%
    Step 3  Start     — promote queued tasks when agents have capacity
    Step 4  Progress  — recompute mission % from completed tasks
    Step 5  Close     — mark missions whose every task is done
    Step 6  Statuses  — sync agent busy/online from live task counts
    Step 7  Recycle   — restart missions that have been completed long enough
    """
    finished = _step_advance_running(db)       # Step 1
    _step_complete_tasks(db, finished)         # Step 2
    _step_start_queued(db)                     # Step 3
    _step_update_mission_progress(db)          # Step 4
    _step_close_missions(db)                   # Step 5
    _step_sync_agent_statuses(db)              # Step 6
    _step_recycle_missions(db)                 # Step 7
    db.commit()


# ─── Background thread ────────────────────────────────────────────────────────

def _run_loop() -> None:
    recycle_label = "enabled" if AUTO_RECYCLE_MISSIONS else "disabled"
    print(f"[orchestrator] loop started  (auto-recycle: {recycle_label})")
    while not _stop_event.is_set():
        try:
            db = SessionLocal()
            _tick(db)
        except Exception as exc:
            print(f"[orchestrator] tick error: {exc}")
        finally:
            db.close()

        _stop_event.wait(TICK_INTERVAL)
    print("[orchestrator] loop stopped")


# ─── Public API (matches original simulator.py interface) ────────────────────

def start() -> None:
    """Start the orchestrator thread.  Safe to call multiple times."""
    global _thread

    if _thread and _thread.is_alive():
        return

    _stop_event.clear()
    _thread = threading.Thread(
        target=_run_loop,
        daemon=True,
        name="pymmys-orchestrator",
    )
    _thread.start()
    print("[orchestrator] started")


def stop() -> None:
    """Signal the orchestrator to stop and wait for it to finish."""
    _stop_event.set()
    if _thread:
        _thread.join(timeout=5.0)
    print("[orchestrator] stopped")
